apiVersion: v1
kind: Service
metadata: 
   name: clusteripsvc
spec:
   selector:
    app: tomapp
   type: ClusterIP
   ports:
   - port: 8080
     targetPort: 8080
     protocol: TCP
     name: tomcat
