apiVersion: v1
kind: Service
metadata: 
   name: lbservice
spec:
   selector:
    app: httpdapp
   type: LoadBalancer
   ports:
   - port: 80
     targetPort: 80
     protocol: TCP
     name: httpd
